V1 sweep
BitGo/wallet-recovery-wizard pull request #455
Opened 2024-07-02 14:05 UTC by rushilbg

2024-07-17 12:44 UTC, OttoAllmendinger requested changes

2024-07-17 12:44 UTC, OttoAllmendinger commented on electron/preload/index.ts
> +  sweepV1(coin: string, parameters);
can we come up with a better type here?

2024-07-17 12:44 UTC, OttoAllmendinger commented on src/containers/V1BtcSweep/index.tsx
> +              setFieldError('unspents', error.message);
why this field?

2024-07-17 13:19 UTC, rushilbg commented on src/containers/V1BtcSweep/index.tsx
> +              setFieldError('unspents', error.message);
Remnant, will update.

2024-07-18 11:34 UTC, OttoAllmendinger approved these changes
issues to be fixed in follow up PR

2024-07-18 11:38 UTC, merged